sudo: required
language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install -y postgresql-contrib-${PG}
  - sudo /etc/init.d/postgresql start ${PG}
  - sleep 5  # to wait for postgres server start

install:
  - python setup.py install
  - pip install -Ur requirements.txt
  - pip install coveralls
  - test $USE_SA == 1 && pip install sqlalchemy || true

before_script:
  - psql -c "create database aiopg;" -U postgres
  - psql -c "create user aiopg with password 'passwd';" -U postgres
  - psql -c "grant all privileges on database aiopg to aiopg;" -U postgres
  - psql -c "create extension hstore;" -U postgres -d aiopg

script:
  - make cov
  - python setup.py check -rms

#addons:
#  postgresql: "9.4"

env:
  global:
    - PYTHON=python
  matrix:
    - USE_SA=1 PYTHONASYNCIODEBUG=x PG=9.3
    - USE_SA=0 PYTHONASYNCIODEBUG=x PG=9.3
    - USE_SA=1 PYTHONASYNCIODEBUG= PG=9.3
    - USE_SA=0 PYTHONASYNCIODEBUG= PG=9.3
#    - USE_SA=1 PYTHONASYNCIODEBUG=1 PG=9.4
#    - USE_SA=0 PYTHONASYNCIODEBUG=1 PG=9.4
#    - USE_SA=1 PYTHONASYNCIODEBUG=0 PG=9.4
#    - USE_SA=0 PYTHONASYNCIODEBUG=0 PG=9.4

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_script:
  - coveralls
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: ZQKbdPT9BlNqP5CTbWRQyeyig7Bpf7wsnYVQIQPOZc9Ec74A+dsbagstR1sPkAO+d+5PN0pZMovvmU7OQhSVPAnJ74nsN90/fL4ux3kqYecMbevv0rJg20hMXSSkwMEIpjUsMdMjJvZAcaKytGWmKL0qAlOJHhixd1pBbWyuIUE=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
